include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enable additional rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    avoid_print: false  # Allow print for logging in this app
    prefer_single_quotes: true
    sort_constructors_first: true
    always_declare_return_types: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false